### ISSUE TITLE
如何可视化？

### ISSUE THREAD

**Issue by 1580827935** [McGregorWwww/UDTransNet#10]
请问能提供可视化代码吗？
![图片](https://github.com/McGregorWwww/UDTransNet/assets/117509706/ec2fe775-1ae2-41cd-b9ab-02202efcbc78)

**Comment by McGregorWwww** [comment]
你好，可视化使用plt做的，只需要在forward取出想要可视化的特征，取mean后加个cmap就好了，可以参考https://blog.csdn.net/dcrmg/article/details/81255498

**Comment by 1580827935** [comment]
感谢您的回答和帮助
