### ISSUE TITLE
Regarding the issue of labelcol

### ISSUE THREAD

**Issue by yese12** [McGregorWwww/UDTransNet#11]
May I ask if I want to replace the label of the dataset with my own, and only need to match a black image of the same size according to the original image size? I didn't see anything else in the black picture

**Comment by McGregorWwww** [comment]
Hi, actually these labels are not pure black, the foreground regions are with very small values, so it seems that they are all black.

**Comment by yese12** [comment]
Thank you for your answer. I am not familiar enough with the GlaS dataset.
