### ISSUE TITLE
运行test时出现问题

### ISSUE THREAD

**Issue by yese12** [McGregorWwww/UDTransNet#13]
你好，我在运行test时因为个人的数据集npy.h5文件图像和标签数据集形状为（38，512，512），会报错ValueError: cannot reshape array of size 9961472 into shape (38,512)，我理解是因为38x512x512=9961472，但我尝试使用您的初始数据集Synapse，发现仍然报错ValueError: cannot reshape array of size 38535168 into shape (147,512)，输出原数据集npy.h5后，图像和标签数据集形状为（147，512，512），我不知道该怎么解决这一问题，期待您的回复

**Comment by yese12** [comment]
我尝试在测试主程序中加入print("config.test_dataset:", config.test_dataset)，得到的结果是config.test_dataset: .\datasets\Synapse\test_vol_h5\，但仍然出现这一问题

**Comment by yese12** [comment]
抱歉，还有一个问题，我在运行test时因为个人的数据集npy.h5文件格式为（38，512，512），会报错ValueError: cannot reshape array of size 9961472 into shape (38,512)，我理解是因为38*512*512=9961472，但我尝试使用您的初始数据集Synapse，发现仍然报错，输出后格式为（137，512，512），我不知道该怎么解决这一问题

**Comment by McGregorWwww** [comment]
抱歉回复的有点晚，这个问题应该是你reshape的目标形状有误，应为(38, 512, 512)，而不是(38, 512)。
