### ISSUE TITLE
关于GlaS数据集的labelcol

### ISSUE THREAD

**Issue by yangning22** [McGregorWwww/UDTransNet#16]
作者您好，我看代码中提供的GlaS数据集的labelcol前景区域值很小，看起来是全黑的，如果我想使用下图这种黑白明显的labelcol的话需要修改Load_Dataset.py吗？
![01](https://github.com/McGregorWwww/UDTransNet/assets/58295484/af73b1c6-d3d9-4ee7-8ec5-a78d475c0804)

**Comment by McGregorWwww** [comment]
你好，不需要的，保证前景大于零就好了：https://github.com/McGregorWwww/UDTransNet/blob/a6dfa392c497d4d5e2c6a742f0cddbf945d95d98/Load_Dataset.py#L168

**Comment by yangning22** [comment]
好的，非常感谢

**Comment by McGregorWwww** [comment]
不客气
