### ISSUE TITLE
性能提升

### ISSUE THREAD

**Issue by heyidashuaige** [McGregorWwww/UDTransNet#2]
你好，请问目前的这个UDTransNet相比于之前的UCTransNet在Glas数据集上有多少的性能提升

**Comment by McGregorWwww** [comment]
你好，感谢关注。其实提升并不是很显著，但是参数量降了很多。
<img width="460" alt="image" src="https://github.com/McGregorWwww/UDTransNet/assets/35693095/60334519-0b2e-4220-ac45-50a7c9bf2aa1">
论文已被接受，很快就会发表。
