### ISSUE TITLE
性能咨询

### ISSUE THREAD

**Issue by chenjh6** [McGregorWwww/UDTransNet#4]
您好，我使用UDtransnet的训练方法（5-folds）在Synapse上训练UCTransNet的网络模型，但是测试的Dice达到了比较惊人的86，请问UDTransNet的测试程序中关于Dice的评判与UCTransNet的是否一致？

**Comment by McGregorWwww** [comment]
你好，感谢关注，是不一致的，因为之前的测试程序其实是有点问题的，尤其是评价指标计算，具体可以参考：https://github.com/Beckschen/TransUNet/issues/39

论文已经被Medical Image Analysis录用，最近很快应该就可以publish，以下是论文中Synapse实验结果的截图，可以先供你参考一下
![image](https://github.com/McGregorWwww/UDTransNet/assets/35693095/d1aca6cf-8bbc-4705-8f69-589dc0b56d71)
