### ISSUE TITLE
多类别分割的test

### ISSUE THREAD

**Issue by ManuJuice** [McGregorWwww/UDTransNet#6]
您好，昨天在您的指导下，我完成了多类别分割的训练，验证集的精度也相当可观，但是在运行test_kfold.py时，遇到了一些问题。

首先，我是基于GlaS数据集的格式创建了我的数据集，并且将task_name设为GlaS进行训练，得到了最终的best_model；

接着，我将Config.py里的test_session改成对应的任务，并运行test_kfold.py，经过我的一系列调整，仍在计算卷积时报错：
  **File "C:\Users\hp\Desktop\ud\nets\UDTransNet.py", line 199, in forward
    e1 = self.Conv1(x)**

报错如下：
**RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 1, 224, 224] to have 3 channels, but got 1 channels instead**

鉴于task_name为GlaS时，test是针对二分类分割任务的，我想向您请教一下，对于多类别分割任务，在test时需要对那些部分做修改？

**Comment by McGregorWwww** [comment]
你好，你这个错误应该是读取图片的问题，GlaS数据集的图片是RGB三通道的，你的应该是1通道灰度图，改一下config里的channel数量就好了

**Comment by ManuJuice** [comment]
> 你好，你这个错误应该是读取图片的问题，GlaS数据集的图片是RGB三通道的，你的应该是1通道灰度图，改一下config里的channel数量就好了

谢谢，已经解决了。不过channel没有错，是读取数据后的处理导致最后输入模型的图片不对

**Comment by watchingyoukk** [comment]
> > 你好，你这个错误应该是读取图片的问题，GlaS数据集的图片是RGB三通道的，你的应该是1通道灰度图，改一下config里的channel数量就好了
> 
> 谢谢，已经解决了。不过channel没有错，是读取数据后的处理导致最后输入模型的图片不对

你好方便问一下修改了哪些可以测试多类的glas的代码吗
