### ISSUE TITLE
测试时出现问题

### ISSUE THREAD

**Issue by wanjianhui** [McGregorWwww/UDTransNet#8]
你好，我最近在尝试复现这个代码，但是在测试时遇到了下面的问题，是哪里没有设置好吗？
![image](https://github.com/McGregorWwww/UDTransNet/assets/67263797/6fa80080-24ec-46e3-9327-62d87c17fbf1)
![image](https://github.com/McGregorWwww/UDTransNet/assets/67263797/d22acb73-4acf-40fc-aeac-316eaf959435)

**Comment by LiangYong1216** [comment]
这个错误表明你尝试将一个大小为 1 的数组重塑为形状 (224, 224)，但是这两个尺寸不匹配。在 NumPy 或类似的库中，reshape 操作用于改变数组的形状，但要确保新形状与原始数组的元素数量相匹配。检查下图片吧

**Comment by spyoning** [comment]
我遇见了相同的问题，希望有人帮我解答一下，我用的库里本就有的数据集

![C`UP6FVKL9H2M@`7M5UD1IE](https://github.com/McGregorWwww/UDTransNet/assets/151030160/fa8af4c7-b566-44a8-9190-c252f8a66661)

**Comment by zhousiis** [comment]
test_session = config.test_session  //这里是配置文件中配置的，改成自己本地的

    for i in range(0,5):
        if config.task_name == "GlaS":
            test_num = 80
            model_type = config.model_name
            model_path = _"./GlaS_kfold/"+model_type+"/"+test_session+"/models/fold_"+str(i+1)+"/best_model-"+model_type+".pth.tar"_

**Comment by spyoning** [comment]
thanks,all right!
