### ISSUE TITLE
评价指标问题

### ISSUE THREAD

**Issue by wanjianhui** [McGregorWwww/UDTransNet#9]
为何论文中使用的评价指标是Dice和HD95，而代码中却是用的Dice和IoU？

**Comment by McGregorWwww** [comment]
你好，代码上传的比较早，后面论文做了修改，可以根据自己的需求替换指标，谢谢

**Comment by 2561995604** [comment]
> 你好，代码上传的比较早，后面论文做了修改，可以根据自己的需求替换指标，谢谢

您好，请问您的HD95指标是如何计算的，可以把这部分代码上传么？
